# Basic Information 
title: Zekun Li (李泽昆)
position: PhD Student
affiliation: Nanjing University
affiliation_link: https://cs.nju.edu.cn
affiliation_logo: ./assets/img/university-logo-small-horizontal-white-156eae9527.svg
email: lizekun (at) smail.nju.edu.cn

# Search Engine Optimization (SEO)
keywords: zekun li, li zekun, zekunli, lizekun, nukezil
canonical: https://nukezil.github.io
description: Zekun Li is a PhD student at Nanjing University.

# The option is used to enable the Johns Hopkins template.
enable_hopkins_logo: false

# The option is used to show the last update time.
enable_last_update: false

# Links
link_type: icon #text/icon
google_scholar: https://scholar.google.com/citations?user=8j3vPD8AAAAJ
# cv_link: https://pages.jh.edu/yliu538/files/Yaoyao_Liu_Curriculum_Vitae.pdf
github_link: https://github.com/nukezil/
# twitter: https://twitter.com/YaoyaoLiu1/

# Images 
avatar: ./assets/img/new_photo.png
# favicon: ./assets/img/favicon.png
# favicon_dark: ./assets/img/favicon-dark.png

# Footnotes
footnote: Thanks to Yaoyao Liu for this homepage template.
footnote_link: https://github.com/yaoyao-liu/minimal-light

# Analytics
# Please remove the following lines about analytics services if you fork my project. 
# Otherwise, the analytics information of your website will be recorded to my ClustrMaps accounts.
clustrmaps_id: dl-x0cezBNpeKqmbRwtIpXWvrQBuO-T4UQMNMKE1vi0

# The following files will be removed from the generated website.
exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
